exclude: |
  (?x)(
    \.snap$
  )
default_stages: [pre-commit]
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: local
    hooks:
      - id: prettier
        name: prettier
        language: system
        types_or: [javascript, ts, svelte, json, yaml]
        entry: yarn run prettier
        args: [--write]

      - id: eslint
        name: eslint
        language: system
        types_or: [javascript, ts, svelte]
        entry: yarn run eslint
        args: [--fix]

      - id: typescript
        name: typescript
        language: system
        types_or: [javascript, ts, svelte]
        pass_filenames: false
        entry: yarn run tsc
        args: [--noEmit]

      - id: vitest
        name: vitest
        language: system
        types_or: [javascript, ts, svelte]
        pass_filenames: false
        entry: yarn run test
