name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    environment: chrome-web-store
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: yarn

      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Build extension
        run: yarn run build

      - name: Create an archive
        run: zip -r raindrop-sync-for-chrome.zip dist

      - name: Preserve build artifact
        uses: actions/upload-artifact@v5
        with:
          name: raindrop-sync-for-chrome
          path: ./raindrop-sync-for-chrome.zip
          retention-days: 14

      - name: Create release
        uses: softprops/action-gh-release@v2.5.0
        with:
          tag_name: ${{ github.event.release.tag_name }}
          generate_release_notes: true
          files: |
            raindrop-sync-for-chrome.zip

      - name: Publish to Chrome Web Store
        uses: MobileFirstLLC/cws-publish@2.1.1
        with:
          action: publish
          extension_id: ${{ vars.CWS_EXTENSION_ID }}
          client_id: ${{ secrets.CWS_CLIENT_ID }}
          client_secret: ${{ secrets.CWS_CLIENT_SECRET }}
          refresh_token: ${{ secrets.CWS_REFRESH_TOKEN }}
          zip_file: ./raindrop-sync-for-chrome.zip
